
CREATE_MAINMENU,
UPDATE_MAINMENU,
DISPLAY_MAINMENU,
EDITED_MAINMENU,

CREATE_FOODMENU,
UPDATE_FOODMENU,
DISPLAY_FOODMENU,
EDITED_FOODMENU,

CREATE_APPETIZERLIST,
UPDATE_APPETIZERLIST,
DISPLAY_APPETIZERLIST,
EDITED_APPETIZERLIST,

CREATE_SOUPLIST,
UPDATE_SOUPLIST,
DISPLAY_SOUPLIST,
EDITED_SOUPLIST,

CREATE_SOUPCHICKENNOODLE,
UPDATE_SOUPCHICKENNOODLE,
DISPLAY_SOUPCHICKENNOODLE,
EDITED_SOUPCHICKENNOODLE,

CREATE_SOUPJAMBALAYA,
UPDATE_SOUPJAMBALAYA,
DISPLAY_SOUPJAMBALAYA,
EDITED_SOUPJAMBALAYA,

CREATE_SOUPSPICYVEGETABLE,
UPDATE_SOUPSPICYVEGETABLE,
DISPLAY_SOUPSPICYVEGETABLE,
EDITED_SOUPSPICYVEGETABLE,

CREATE_SOUPSCHEESYBROCCOLI,
UPDATE_SOUPSCHEESYBROCCOLI,
DISPLAY_SOUPSCHEESYBROCCOLI,
EDITED_SOUPSCHEESYBROCCOLI,

CREATE_SOUPCREAMYTOMATO,
UPDATE_SOUPCREAMYTOMATO,
DISPLAY_SOUPCREAMYTOMATO,
EDITED_SOUPCREAMYTOMATO,

CREATE_SOUPBEAN,
UPDATE_SOUPBEAN,
DISPLAY_SOUPBEAN,
EDITED_SOUPBEAN,

CREATE_SOUPITALIANWEDDING,
UPDATE_SOUPITALIANWEDDING,
DISPLAY_SOUPITALIANWEDDING,
EDITED_SOUPITALIANWEDDING,

CREATE_GUMBOSOUP,
UPDATE_GUMBOSOUP,
DISPLAY_GUMBOSOUP,
EDITED_GUMBOSOUP,

CREATE_SOUPFISH,
UPDATE_SOUPFISH,
DISPLAY_SOUPFISH,
EDITED_SOUPFISH,

CREATE_SOUPCREAMYMUSHROOM,
UPDATE_SOUPCREAMYMUSHROOM,
DISPLAY_SOUPCREAMYMUSHROOM,
EDITED_SOUPCREAMYMUSHROOM,

CREATE_SANDWICHESLIST,
UPDATE_SANDWICHESLIST,
DISPLAY_SANDWICHESLIST,
EDITED_SANDWICHESLIST,

CREATE_SANDWICHESLIST2,
UPDATE_SANDWICHESLIST2,
DISPLAY_SANDWICHESLIST2,
EDITED_SANDWICHESLIST2,

CREATE_APPETFRIEDPICKLES,
UPDATE_APPETFRIEDPICKLES,
DISPLAY_APPETFRIEDPICKLES,
EDITED_APPETFRIEDPICKLES,

CREATE_APPETCHEESESTICK,
UPDATE_APPETCHEESESTICK,
DISPLAY_APPETCHEESESTICK,
EDITED_APPETCHEESESTICK,

CREATE_APPETCHILIFRIE,
UPDATE_APPETCHILIFRIE,
DISPLAY_APPETCHILIFRIE,
EDITED_APPETCHILIFRIE,

CREATE_APPETFAIRFRIE,
UPDATE_APPETFAIRFRIE,
DISPLAY_APPETFAIRFRIE,
EDITED_APPETFAIRFRIE,

CREATE_APPETGARLICFAIRFRIES,
UPDATE_APPETGARLICFAIRFRIES,
DISPLAY_APPETGARLICFAIRFRIES,
EDITED_APPETGARLICFAIRFRIES,

CREATE_APPETCARROTFRIES,
UPDATE_APPETCARROTFRIES,
DISPLAY_APPETCARROTFRIES,
EDITED_APPETCARROTFRIES,

CREATE_APPETFRIEDGREENBEANS,
UPDATE_APPETFRIEDGREENBEANS,
DISPLAY_APPETFRIEDGREENBEANS,
EDITED_APPETFRIEDGREENBEANS,

CREATE_APPETMEXICANNACHOS,
UPDATE_APPETMEXICANNACHOS,
DISPLAY_APPETMEXICANNACHOS,
EDITED_APPETMEXICANNACHOS,

CREATE_APPETSPICYNACHOS,
UPDATE_APPETSPICYNACHOS,
DISPLAY_APPETSPICYNACHOS,
EDITED_APPETSPICYNACHOS,

CREATE_APPETORINGS,
UPDATE_APPETORINGS,
DISPLAY_APPETORINGS,
EDITED_APPETORINGS,

CREATE_SANDTURKEYCLUB,
UPDATE_SANDTURKEYCLUB,
DISPLAY_SANDTURKEYCLUB,
EDITED_SANDTURKEYCLUB,

CREATE_SANDREUBEN,
UPDATE_SANDREUBEN,
DISPLAY_SANDREUBEN,
EDITED_SANDREUBEN,

CREATE_SANDVEGGIEREUBEN,
UPDATE_SANDVEGGIEREUBEN,
DISPLAY_SANDVEGGIEREUBEN,
EDITED_SANDVEGGIEREUBEN,

CREATE_SANDSMOTHERED,
UPDATE_SANDSMOTHERED,
DISPLAY_SANDSMOTHERED,
EDITED_SANDSMOTHERED,

CREATE_SANDSMOTHEREDBUFFALO,
UPDATE_SANDSMOTHEREDBUFFALO,
DISPLAY_SANDSMOTHEREDBUFFALO,
EDITED_SANDSMOTHEREDBUFFALO,

CREATE_SANDCORNDOG,
UPDATE_SANDCORNDOG,
DISPLAY_SANDCORNDOG,
EDITED_SANDCORNDOG,

CREATE_SANDSTEAKINAWRAP,
UPDATE_SANDSTEAKINAWRAP,
DISPLAY_SANDSTEAKINAWRAP,
EDITED_SANDSTEAKINAWRAP,

CREATE_SANDGARDENSANDWICH,
UPDATE_SANDGARDENSANDWICH,
DISPLAY_SANDGARDENSANDWICH,
EDITED_SANDGARDENSANDWICH,

CREATE_SANDGRILLEDCHICKEN,
UPDATE_SANDGRILLEDCHICKEN,
DISPLAY_SANDGRILLEDCHICKEN,
EDITED_SANDGRILLEDCHICKEN,

CREATE_SANDCAJUN,
UPDATE_SANDCAJUN,
DISPLAY_SANDCAJUN,
EDITED_SANDCAJUN,

CREATE_SANDFRIEDSTACKER,
UPDATE_SANDFRIEDSTACKER,
DISPLAY_SANDFRIEDSTACKER,
EDITED_SANDFRIEDSTACKER,

CREATE_SANDGRILLEDSTACKER,
UPDATE_SANDGRILLEDSTACKER,
DISPLAY_SANDGRILLEDSTACKER,
EDITED_SANDGRILLEDSTACKER,

CREATE_SANDBLACKENEDTILAPIA,
UPDATE_SANDBLACKENEDTILAPIA,
DISPLAY_SANDBLACKENEDTILAPIA,
EDITED_SANDBLACKENEDTILAPIA,

CREATE_SANDVEGGIEMUSHROOM,
UPDATE_SANDVEGGIEMUSHROOM,
DISPLAY_SANDVEGGIEMUSHROOM,
EDITED_SANDVEGGIEMUSHROOM,

CREATE_SANDGRILLEDCHEESE,
UPDATE_SANDGRILLEDCHEESE,
DISPLAY_SANDGRILLEDCHEESE,
EDITED_SANDGRILLEDCHEESE,

CREATE_BURGERLIST,
UPDATE_BURGERLIST,
DISPLAY_BURGERLIST,
EDITED_BURGERLIST,

CREATE_BURGERCHEESE,
UPDATE_BURGERCHEESE,
DISPLAY_BURGERCHEESE,
EDITED_BURGERCHEESE,

CREATE_BURGERHAM,
UPDATE_BURGERHAM,
DISPLAY_BURGERHAM,
EDITED_BURGERHAM,

CREATE_BURGERPEPPER,
UPDATE_BURGERPEPPER,
DISPLAY_BURGERPEPPER,
EDITED_BURGERPEPPER,

CREATE_BURGERCAJUN,
UPDATE_BURGERCAJUN,
DISPLAY_BURGERCAJUN,
EDITED_BURGERCAJUN,

CREATE_BURGERMONSTER,
UPDATE_BURGERMONSTER,
DISPLAY_BURGERMONSTER,
EDITED_BURGERMONSTER,

CREATE_BURGERMUSHROOM,
UPDATE_BURGERMUSHROOM,
DISPLAY_BURGERMUSHROOM,
EDITED_BURGERMUSHROOM,

CREATE_SALADSLIST1,
UPDATE_SALADSLIST1,
DISPLAY_SALADSLIST1,
EDITED_SALADSLIST1,

CREATE_SALADLIST2,
UPDATE_SALADLIST2,
DISPLAY_SALADLIST2,
EDITED_SALADLIST2,

CREATE_SALADVEGETABLE,
UPDATE_SALADVEGETABLE,
DISPLAY_SALADVEGETABLE,
EDITED_SALADVEGETABLE,

CREATE_SALADSPICYVEG,
UPDATE_SALADSPICYVEG,
DISPLAY_SALADSPICYVEG,
EDITED_SALADSPICYVEG,

CREATE_SALADSUPREMETACO,
UPDATE_SALADSUPREMETACO,
DISPLAY_SALADSUPREMETACO,
EDITED_SALADSUPREMETACO,

CREATE_SALADLEMONSHRIMP,
UPDATE_SALADLEMONSHRIMP,
DISPLAY_SALADLEMONSHRIMP,
EDITED_SALADLEMONSHRIMP,

CREATE_SALADHAM,
UPDATE_SALADHAM,
DISPLAY_SALADHAM,
EDITED_SALADHAM,

CREATE_SALADFRIEDCHICKEN,
UPDATE_SALADFRIEDCHICKEN,
DISPLAY_SALADFRIEDCHICKEN,
EDITED_SALADFRIEDCHICKEN,

CREATE_SALADSTEAK,
UPDATE_SALADSTEAK,
DISPLAY_SALADSTEAK,
EDITED_SALADSTEAK,

CREATE_SALADFRUIT,
UPDATE_SALADFRUIT,
DISPLAY_SALADFRUIT,
EDITED_SALADFRUIT,

CREATE_SALADFETAFRUIT,
UPDATE_SALADFETAFRUIT,
DISPLAY_SALADFETAFRUIT,
EDITED_SALADFETAFRUIT,

CREATE_SALADBLACKENEDTIL,
UPDATE_SALADBLACKENEDTIL,
DISPLAY_SALADBLACKENEDTIL,
EDITED_SALADBLACKENEDTIL,

CREATE_SALADGARDEN,
UPDATE_SALADGARDEN,
DISPLAY_SALADGARDEN,
EDITED_SALADGARDEN,

CREATE_SALADBACONATOR,
UPDATE_SALADBACONATOR,
DISPLAY_SALADBACONATOR,
EDITED_SALADBACONATOR,

CREATE_DESSAPPLE,
UPDATE_DESSAPPLE,
DISPLAY_DESSAPPLE,
EDITED_DESSAPPLE,

CREATE_DESSERTSLIST,
UPDATE_DESSERTSLIST,
DISPLAY_DESSERTSLIST,
EDITED_DESSERTSLIST,

CREATE_DESSBLUE,
UPDATE_DESSBLUE,
DISPLAY_DESSBLUE,
EDITED_DESSBLUE,

CREATE_DESSBROWNIE,
UPDATE_DESSBROWNIE,
DISPLAY_DESSBROWNIE,
EDITED_DESSBROWNIE,

CREATE_DESSMOUSSE,
UPDATE_DESSMOUSSE,
DISPLAY_DESSMOUSSE,
EDITED_DESSMOUSSE,

CREATE_DESSPEANUT,
UPDATE_DESSPEANUT,
DISPLAY_DESSPEANUT,
EDITED_DESSPEANUT,

CREATE_DESSREDVEL,
UPDATE_DESSREDVEL,
DISPLAY_DESSREDVEL,
EDITED_DESSREDVEL,

CREATE_DESSSTRAW,
UPDATE_DESSSTRAW,
DISPLAY_DESSSTRAW,
EDITED_DESSSTRAW,

CREATE_DESSSUNDAE,
UPDATE_DESSSUNDAE,
DISPLAY_DESSSUNDAE,
EDITED_DESSSUNDAE,

CREATE_DINCORNBEEF,
UPDATE_DINCORNBEEF,
DISPLAY_DINCORNBEEF,
EDITED_DINCORNBEEF,

CREATE_DINNERLIST,
UPDATE_DINNERLIST,
DISPLAY_DINNERLIST,
EDITED_DINNERLIST,

CREATE_DINFRIEDCHIKEN,
UPDATE_DINFRIEDCHIKEN,
DISPLAY_DINFRIEDCHIKEN,
EDITED_DINFRIEDCHIKEN,

CREATE_DINGRILLEDCHICKEN,
UPDATE_DINGRILLEDCHICKEN,
DISPLAY_DINGRILLEDCHICKEN,
EDITED_DINGRILLEDCHICKEN,

CREATE_DINLASAGNA,
UPDATE_DINLASAGNA,
DISPLAY_DINLASAGNA,
EDITED_DINLASAGNA,

CREATE_DINMARPIZZA,
UPDATE_DINMARPIZZA,
DISPLAY_DINMARPIZZA,
EDITED_DINMARPIZZA,

CREATE_DINQUESADILLA,
UPDATE_DINQUESADILLA,
DISPLAY_DINQUESADILLA,
EDITED_DINQUESADILLA,

CREATE_DINSPAGHETTI,
UPDATE_DINSPAGHETTI,
DISPLAY_DINSPAGHETTI,
EDITED_DINSPAGHETTI,

CREATE_DINSTEAK,
UPDATE_DINSTEAK,
DISPLAY_DINSTEAK,
EDITED_DINSTEAK,

CREATE_DINTILAPIA,
UPDATE_DINTILAPIA,
DISPLAY_DINTILAPIA,
EDITED_DINTILAPIA,

CREATE_DINVEGPIZZA,
UPDATE_DINVEGPIZZA,
DISPLAY_DINVEGPIZZA,
EDITED_DINVEGPIZZA,

CREATE_SIDESLIST,
UPDATE_SIDESLIST,
DISPLAY_SIDESLIST,
EDITED_SIDESLIST,

CREATE_SIDESBAKEDPOT,
UPDATE_SIDESBAKEDPOT,
DISPLAY_SIDESBAKEDPOT,
EDITED_SIDESBAKEDPOT,

CREATE_SIDESBROCCOLI,
UPDATE_SIDESBROCCOLI,
DISPLAY_SIDESBROCCOLI,
EDITED_SIDESBROCCOLI,

CREATE_SIDESFRIES,
UPDATE_SIDESFRIES,
DISPLAY_SIDESFRIES,
EDITED_SIDESFRIES,

CREATE_SIDESFRUIT,
UPDATE_SIDESFRUIT,
DISPLAY_SIDESFRUIT,
EDITED_SIDESFRUIT,

CREATE_SIDESMASHED,
UPDATE_SIDESMASHED,
DISPLAY_SIDESMASHED,
EDITED_SIDESMASHED,

CREATE_SIDESORINGS,
UPDATE_SIDESORINGS,
DISPLAY_SIDESORINGS,
EDITED_SIDESORINGS,

CREATE_SIDESSLAW,
UPDATE_SIDESSLAW,
DISPLAY_SIDESSLAW,
EDITED_SIDESSLAW,
